/**
 * PRIME CONTROL V1.4F — GPTMaker-native Story fallback routing contract.
 *
 * Policy decision only. Zero I/O, zero model calls, no customer text generation
 * and no connection to an agent's inbound/outbound message handlers.
 * The NATIVE GPTMaker training remains the authority for the actual wording.
 *
 * This module is a LAB *harness*: it MUST NOT be imported in the production
 * webhook or installed as an automatic reply path without a separate approval.
 */
export const NATIVE_STORY_PRINT_TRAINING='3F9C22DD0477D04D51EC72B5AF3F6A41'
export const NATIVE_STORY_CONFIDENCE_TRAINING='3F90779F309300BCD5BD426E229A42AC'
export const REAL_STORY_FINGERPRINT='e7724e511a7e661c68aadfd9'
export const ALLOWED_SCOPE='GABY_LAB_COMERCIAL'
const isObj=x=>x!=null&&typeof x==='object'&&!Array.isArray(x)

/**
 * SAFE DEMO CONTRACT:
 * - A Gemini estimate of 90% is not a calibrated probability.
 * - Native HIGH/MEDIUM/LOW labels are NOT derived from the raw Gemini score.
 * - An existing BLOCK from JEV cannot be overridden by Visual Match or text.
 * - Mere presence of a catalog candidate does not verify the exact model.
 * - Customer-facing language MUST be generated by GPTMaker's native training,
 *   not by a duplicate custom assistant.
 */
export function routeToNativeStoryTraining(s={}){
 const base={
  mode:'LAB_POLICY_PREVIEW_ONLY',
  route:'BLOCK',
  training_id:null,
  reason:'INVALID_INPUT',
  messages_sent:0,external_calls:0,vision_calls:0,jev_calls:0,catalog_calls:0,
  price_allowed:false,pix_allowed:false,stock_allowed:false,
  exact_product_assertion_allowed:false,
  intended_delivery:'NONE',
 }
 if(!isObj(s)||s.scope!==ALLOWED_SCOPE)
  return {...base,reason:'OUTSIDE_LAB_SCOPE'}
 if(s.context_status!=='FOUND'){
  return {...base,route:'GPTMAKER_NATIVE_DEFAULT',reason:'NO_VERIFIED_STORY_CONTEXT',
   intended_delivery:'GPTMAKER_NATIVE_ONLY'}
 }
 if(typeof s.story_fingerprint!=='string'||!/^([a-f0-9]{24})$/.test(s.story_fingerprint)){
  return {...base,route:'BLOCK',reason:'STORY_FINGERPRINT_INVALID'}
 }
 if(s.story_fingerprint!==REAL_STORY_FINGERPRINT){
  return {...base,route:'BLOCK',reason:'DIFFERENT_STORY_REQUIRES_OWN_CORRELATION'}
 }
 const fromScreenshot=s.media_source==='USER_UPLOADED_IMAGE'
 const verified=s.catalog?.status==='READ_ONLY_OK' &&
  s.catalog?.exact_sku_verified===true &&
  s.jev?.status==='ok'&&s.jev?.action==='ALLOW_AUTO' &&
  s.visual?.status==='STRONG_VISUAL_MATCH'&&s.visual?.choice==='C1'&&
  Number.isFinite(s.visual?.confidence)&&s.visual.confidence>=0.95
 if(verified){
  return {...base,
   route:'GPTMAKER_NATIVE_CONFIRMED_CATALOG',
   training_id:NATIVE_STORY_CONFIDENCE_TRAINING,
   reason:'ALL_INDEPENDENT_GATES_PASSED',
   intended_delivery:'NATIVE_GPTMAKER_AFTER_SEPARATE_INTEGRATION',
   exact_product_assertion_allowed:true,
   // An explicitly verified catalog SKU still does not validate a commercial
   // price, a payment condition or physical availability by itself.
   price_allowed:s.catalog?.price_verified===true,
   pix_allowed:false,
   stock_allowed:s.catalog?.physical_stock_verified===true,
  }
 }
 if(fromScreenshot){
  // Do NOT ask again for the picture that is already attached.
  // The existing native confidence guidance uses ONE useful clarification.
  return {...base,route:'GPTMAKER_NATIVE_SINGLE_DETAIL',
   training_id:NATIVE_STORY_CONFIDENCE_TRAINING,
   reason:'UPLOAD_PRESENT_BUT_EXACT_PRODUCT_UNCONFIRMED',
   intended_delivery:'NATIVE_GPTMAKER_AFTER_SEPARATE_INTEGRATION'}
 }
 return {...base,
  route:'GPTMAKER_NATIVE_REQUEST_STORY_PRINT',
  training_id:NATIVE_STORY_PRINT_TRAINING,
  reason:s.jev?.action==='BLOCK_ASSERTION'?'JEV_BLOCKS_MODEL_ASSERTION':
   'STORY_MODEL_NOT_CONFIRMED',
  intended_delivery:'NATIVE_GPTMAKER_AFTER_SEPARATE_INTEGRATION',
 }
}

// Four immutable proof scenarios: real outcomes + safety counterfactuals.
export const V14F_CASES=Object.freeze([
 {name:'VANS_REAL_90PCT_JEV_BLOCK',input:{
  scope:ALLOWED_SCOPE,context_status:'FOUND',story_fingerprint:REAL_STORY_FINGERPRINT,
  media_source:'INSTAGRAM_STORY',
  catalog:{status:'READ_ONLY_OK',candidates:1,exact_sku_verified:false},
  visual:{status:'VISUAL_UNCERTAIN',choice:'C1',confidence:0.90},
  jev:{status:'ok',action:'BLOCK_ASSERTION',confidence:0.06},
 },expected:'GPTMAKER_NATIVE_REQUEST_STORY_PRINT'},
 {name:'HIGH_VISUAL_BUT_JEV_STILL_BLOCKS',input:{
  scope:ALLOWED_SCOPE,context_status:'FOUND',story_fingerprint:REAL_STORY_FINGERPRINT,
  media_source:'INSTAGRAM_STORY',
  catalog:{status:'READ_ONLY_OK',candidates:1,exact_sku_verified:false},
  visual:{status:'STRONG_VISUAL_MATCH',choice:'C1',confidence:0.99},
  jev:{status:'ok',action:'BLOCK_ASSERTION',confidence:0.06},
 },expected:'GPTMAKER_NATIVE_REQUEST_STORY_PRINT'},
 {name:'REUPLOADED_SCREENSHOT_REQUIRES_ONE_DETAIL',input:{
  scope:ALLOWED_SCOPE,context_status:'FOUND',story_fingerprint:REAL_STORY_FINGERPRINT,
  media_source:'USER_UPLOADED_IMAGE',
  catalog:{status:'READ_ONLY_OK',exact_sku_verified:false},
  visual:{status:'VISUAL_UNCERTAIN',choice:'C1',confidence:0.90},
  jev:{status:'ok',action:'BLOCK_ASSERTION'},
 },expected:'GPTMAKER_NATIVE_SINGLE_DETAIL'},
 {name:'EXACT_MODEL_AND_ALL_INDEPENDENT_GATES',input:{
  scope:ALLOWED_SCOPE,context_status:'FOUND',story_fingerprint:REAL_STORY_FINGERPRINT,
  media_source:'INSTAGRAM_STORY',
  catalog:{status:'READ_ONLY_OK',exact_sku_verified:true,
   price_verified:false,physical_stock_verified:false},
  visual:{status:'STRONG_VISUAL_MATCH',choice:'C1',confidence:0.97},
  jev:{status:'ok',action:'ALLOW_AUTO',confidence:0.98},
 },expected:'GPTMAKER_NATIVE_CONFIRMED_CATALOG'},
])
export function simulateNativeFallbackScenarios(){
 const cases=V14F_CASES.map(x=>{
  const answer=routeToNativeStoryTraining(x.input)
  return {scenario:x.name,expected:x.expected,actual:answer.route,
   passed:answer.route===x.expected&&answer.messages_sent===0&&
    answer.external_calls===0&&answer.vision_calls===0&&answer.jev_calls===0&&
    answer.catalog_calls===0,training_id:answer.training_id,
   price_allowed:answer.price_allowed,exact_product_assertion_allowed:answer.exact_product_assertion_allowed}
 })
 return {ok:cases.every(x=>x.passed),
  mode:'PURE_LAB_SIMULATION',
  scenarios:cases,
  messages_sent:0,external_calls:0,vision_calls:0,jev_calls:0,catalog_calls:0,
  training_modified:false,gaby_official_modified:false,
  actual_gptmaker_response_tested:false}
}
